// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUMTYWwTjvo8pTtTtyop3cZxMwvdQ6Ibk',
    appId: '1:731949676966:web:d86f4a17c99f907e1d3767',
    messagingSenderId: '731949676966',
    projectId: 'inquire-near-2022',
    authDomain: 'inquire-near-2022.firebaseapp.com',
    storageBucket: 'inquire-near-2022.appspot.com',
    measurementId: 'G-SP8XW417CF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN0u9A03m9_nz3kQ0DCmDothQPx-5LTXQ',
    appId: '1:731949676966:android:ebb45561203a47371d3767',
    messagingSenderId: '731949676966',
    projectId: 'inquire-near-2022',
    storageBucket: 'inquire-near-2022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVRcawRoOL7Bvmy5TYKK5Yw24M7VMalgQ',
    appId: '1:731949676966:ios:3ca5b85e36682d771d3767',
    messagingSenderId: '731949676966',
    projectId: 'inquire-near-2022',
    storageBucket: 'inquire-near-2022.appspot.com',
    androidClientId: '731949676966-dp8t0p6qmu0l5dna42csdd2ogka478dh.apps.googleusercontent.com',
    iosClientId: '731949676966-aj7fu693cqd4atfjfvvj09hr5thfpakl.apps.googleusercontent.com',
    iosBundleId: 'com.example.inquireNear',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVRcawRoOL7Bvmy5TYKK5Yw24M7VMalgQ',
    appId: '1:731949676966:ios:3ca5b85e36682d771d3767',
    messagingSenderId: '731949676966',
    projectId: 'inquire-near-2022',
    storageBucket: 'inquire-near-2022.appspot.com',
    androidClientId: '731949676966-dp8t0p6qmu0l5dna42csdd2ogka478dh.apps.googleusercontent.com',
    iosClientId: '731949676966-aj7fu693cqd4atfjfvvj09hr5thfpakl.apps.googleusercontent.com',
    iosBundleId: 'com.example.inquireNear',
  );
}
